# Generated by Django 4.0.2 on 2022-02-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ('pk',), 'verbose_name': 'Plant', 'verbose_name_plural': 'Plants'},
        ),
        migrations.AlterField(
            model_name='plantedtrees',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Lat'),
        ),
        migrations.AlterField(
            model_name='plantedtrees',
            name='location_long',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Long'),
        ),
    ]
