# Generated by Django 4.0.2 on 2022-02-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0003_alter_plantedtrees_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtrees',
            name='planted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planted at'),
        ),
    ]
