# Generated by Django 4.0.2 on 2022-02-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0005_alter_plantedtrees_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtrees',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Lat'),
        ),
        migrations.AlterField(
            model_name='plantedtrees',
            name='location_long',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Long'),
        ),
    ]
